repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check
        language: system
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]

      - id: taplo-format
        name: taplo format
        entry: uv run taplo fmt --check
        language: system
        types: [toml]

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
